# This is a generated file. Not intended for manual editing.
services:
  evently.api:
    build:
      context: "/Users/mohammadmeftauddin/RiderProjects/Evently.April14"
      dockerfile: "src/API/Evently.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Evently.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "evently.api:dev"
    ports: []
    volumes:
    - "/Users/mohammadmeftauddin/RiderProjects/Evently.April14/src/API/Evently.Api:/app:rw"
    - "/Users/mohammadmeftauddin/RiderProjects/Evently.April14:/src:rw"
    - "/Users/mohammadmeftauddin/.nuget/packages:/root/.nuget/packages"
    working_dir: "/app"
